[package]
name = "day17"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

<<<<<<< HEAD
[dependencies]
utils = { path = "../../utils" }
=======
[[bin]]
name = "debug"
path = "./src/debug.rs"

[dependencies]
utils = { path = "../../utils" }
regex = "1.5.4"
>>>>>>> 86ee6b943362c3b8c0810cfc88903432b54f5bc5
